In [2]:
import numpy as np

In [2]:
list1= [10,20,30,40,50]
numpy=np.array([list1])

print(numpy)

[[10 20 30 40 50]]


In [3]:
print(type(numpy))

<class 'numpy.ndarray'>


In [4]:
lis = [50,60,70,80,90,True,False]
lis1 =np.array(lis)

print(lis1)

[50 60 70 80 90  1  0]


In [5]:
lis = [50,60,70,80,90,True,False,50.5]
lis1 =np.array(lis)

print(lis1)

[50.  60.  70.  80.  90.   1.   0.  50.5]


In [6]:
lis2 = [50,60,70,80,90,True,False,50.5,'Rohan']
lis3 =np.array(lis2)

print(lis3)

['50' '60' '70' '80' '90' 'True' 'False' '50.5' 'Rohan']


In [7]:
print(type(lis3[2]))

<class 'numpy.str_'>


In [8]:
l1=[[1,2,3,4,5],[6,7,8,9,np.nan]]
l2=np.array(l1)

print(l2)

print(l2.ndim,'dimention')

print('shape is',l2.shape)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. nan]]
2 dimention
shape is (2, 5)


In [9]:
print(l2*2)

[[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. nan]]


In [16]:
list1= [10,20,30]
list2 = [50,55,56]
arr= np.array([list1,list2])

print(arr)

[[10 20 30]
 [50 55 56]]


In [19]:
print(type(arr))

<class 'numpy.ndarray'>


In [20]:
list2=np.array([10,20,30,50,55,56])
list3=list2[1:-2]
list3[1]=40

print(list2)
print(list3)

[10 20 40 50 55 56]
[20 40 50]


In [21]:
l1=list2.copy()
print(l1)

l1[4:]=60,70
print(l1)

[10 20 40 50 55 56]
[10 20 40 50 60 70]


In [31]:
arr = np.arange(10,100,5)

print(arr)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [32]:
arr = np.arange(100,200,10)
print(arr)

[100 110 120 130 140 150 160 170 180 190]


In [33]:
arr = np.arange(10,100)

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [34]:
ar =np.arange(30)
ar.reshape(2,5,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [35]:
ar =np.arange(40)

ar.reshape(5,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [47]:
ar =np.arange(40)
ar.reshape(2,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

In [44]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
b = np.ones((2,5,5))
b

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [50]:
x = [1,2,3]
a = np.array(x, dtype=float)

print (a)
print(type(x))

print(type(a))


[1. 2. 3.]
<class 'list'>
<class 'numpy.ndarray'>


In [51]:
c =b.astype(str)
c

array([[['1.0', '1.0', '1.0', '1.0', '1.0'],
        ['1.0', '1.0', '1.0', '1.0', '1.0'],
        ['1.0', '1.0', '1.0', '1.0', '1.0'],
        ['1.0', '1.0', '1.0', '1.0', '1.0'],
        ['1.0', '1.0', '1.0', '1.0', '1.0']],

       [['1.0', '1.0', '1.0', '1.0', '1.0'],
        ['1.0', '1.0', '1.0', '1.0', '1.0'],
        ['1.0', '1.0', '1.0', '1.0', '1.0'],
        ['1.0', '1.0', '1.0', '1.0', '1.0'],
        ['1.0', '1.0', '1.0', '1.0', '1.0']]], dtype='<U32')

In [52]:
c =b.astype(bool)
c

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [53]:
a =np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
c=a.astype(bool)
c

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [57]:
list1 = [10,20,30,40,50,'X']
array1 = np.array (list1)

print (type(list1))
print (type(array1))


print (list1)
print (array1)


<class 'list'>
<class 'numpy.ndarray'>
[10, 20, 30, 40, 50, 'X']
['10' '20' '30' '40' '50' 'X']


In [59]:
lis = np.array (list1)
print(lis)


['10' '20' '30' '40' '50' 'X']


In [66]:
a =np.dtype(np.int16)
a

dtype('int16')

In [67]:
Tup1 = (10,20,30,40,50,'x','y')

ar = np.array(Tup1)


print(Tup1)
print(ar)


print(type(ar))
print(type(Tup1))

(10, 20, 30, 40, 50, 'x', 'y')
['10' '20' '30' '40' '50' 'x' 'y']
<class 'numpy.ndarray'>
<class 'tuple'>


In [3]:
a = np.arange(9)
a = a.reshape((3,3))
print (a)
print (a[1][1])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


In [4]:
a = np.arange(9)
a = a.reshape((3,3))

print (a)
print (a[2][2])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
8


In [5]:
x = np.arange(0,30)
i = np.reshape(x,(6,5),'F')

print(x)

print(i)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [6]:
x = np.arange(0,30)
i = np.reshape(x,(6,5))

print(x)

print(i)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [7]:
ar = np.arange(0,20,5)

print(ar)

[ 0  5 10 15]


In [8]:
arr = np.linspace(0,20,5)

print(arr)

[ 0.  5. 10. 15. 20.]


In [9]:
z = np.arange(1, 1.3, 0.1)
z

array([1. , 1.1, 1.2, 1.3])

In [13]:
arr = np.linspace(5,50,11)

print(arr)

[ 5.   9.5 14.  18.5 23.  27.5 32.  36.5 41.  45.5 50. ]


In [14]:
list1 = [10,20,30,40]
list2 = [100,110,120,130]
list3 = [200,210,220,230]
Mat1 = np.array ([list1, list2,list3])

print (Mat1)

print('......................')

print (Mat1.T)   


[[ 10  20  30  40]
 [100 110 120 130]
 [200 210 220 230]]
......................
[[ 10 100 200]
 [ 20 110 210]
 [ 30 120 220]
 [ 40 130 230]]


In [15]:
a=np.array([1, 2, 3,4,5], ndmin=3)

print(a)

[[[1 2 3 4 5]]]


In [16]:
a=np.array([1, 2, 3,4,5], dtype=complex)

print(a)

print(type(a[1]))

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
<class 'numpy.complex128'>


In [17]:
a=np.array([0,1, 2, 3,4,5], dtype=bool)

print(a)
print(type(a[1]))

[False  True  True  True  True  True]
<class 'numpy.bool_'>


In [18]:
a=np.uint32([0,1, 2, 3,4,5])

print(a)
print(type(a[1]))

[0 1 2 3 4 5]
<class 'numpy.uint32'>


In [22]:

student=np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])

print (student['name'])

print(type(student))

|S20
<class 'numpy.dtype[void]'>


In [25]:
student=np.array([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
print (student)

print (type(student))

[['name' 'S20']
 ['age' 'i1']
 ['marks' 'f4']]
<class 'numpy.ndarray'>


In [26]:
tup=(1,2,3),(5,6,7)
arr = np.array(tup)
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [28]:
tup=[(1,2,3),(5,6,7)]
arr = np.array(tup)

print(arr)

[[1 2 3]
 [5 6 7]]


In [ ]:
tup=[(1,2,3),(5,6,7)]
arr = np.array(tup)
print(arr)

print(type(arr))

In [29]:
import numpy as np

list1 = [10,20,30,40]
list2 = [100,110,120,130]
list3 = [200,210,220,230]
Mat1 = np.array ([list1, list2,list3])

print (Mat1)
print('\n')
print (Mat1.T)  


[[ 10  20  30  40]
 [100 110 120 130]
 [200 210 220 230]]


[[ 10 100 200]
 [ 20 110 210]
 [ 30 120 220]
 [ 40 130 230]]


In [30]:
print('\n')

print(np.reshape(Mat1,(6,2),'F'))



[[ 10  30]
 [100 120]
 [200 220]
 [ 20  40]
 [110 130]
 [210 230]]


In [34]:
a = np.arange(5,14)

b = a.reshape(3,3)
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [33]:
d = np.arange(1,10)
c=d.reshape(3,3)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
b+c

array([[ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [37]:
b*c

array([[  5,  12,  21],
       [ 32,  45,  60],
       [ 77,  96, 117]])

In [38]:
b/c

array([[5.        , 3.        , 2.33333333],
       [2.        , 1.8       , 1.66666667],
       [1.57142857, 1.5       , 1.44444444]])

In [39]:
b%c

array([[0, 0, 1],
       [0, 4, 4],
       [4, 4, 4]], dtype=int32)

In [40]:
b@c

array([[ 78,  96, 114],
       [114, 141, 168],
       [150, 186, 222]])

In [44]:
x = np.arange(1,31)

print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [45]:
z=x.reshape(5,6)
print(z)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [46]:
n= z.ravel()
n


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [47]:
12/8

1.5

In [49]:
8//4

2

In [50]:
list1 = [500,510,520,530]
list2 = [100,110,120,130]
list3 = [200,210,220,230]
Mat1 = np.array ([list1, list2,list3])

print(Mat1)

[[500 510 520 530]
 [100 110 120 130]
 [200 210 220 230]]


In [51]:
list6 = [10,11,12,13]
list7 = [20,21,22,23]
list8 = [30,31,32,33]
Mat2 = np.array ([list6, list7,list8])

print(Mat2)

[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


In [52]:
Mat3 = Mat1/Mat2
print (Mat3)


[[50.         46.36363636 43.33333333 40.76923077]
 [ 5.          5.23809524  5.45454545  5.65217391]
 [ 6.66666667  6.77419355  6.875       6.96969697]]


In [53]:
Mat3 = Mat1//Mat2
print (Mat3)


[[50 46 43 40]
 [ 5  5  5  5]
 [ 6  6  6  6]]


In [54]:
list6 = [10,11,12,13]
list7 = [20,21,22,23]
list8 = [30,31,32,33]
Mat2 = np.array ([list6, list7,list8])

print(Mat2)

[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


In [55]:
mat =Mat2.ravel()

print(mat)

[10 11 12 13 20 21 22 23 30 31 32 33]


In [56]:
lin =np.linspace(0,30,6)
lin

array([ 0.,  6., 12., 18., 24., 30.])

In [57]:
EU_Sales = [1002, 4523,4123,3584]
APAC_Sales = [7854,9654,4582,8543]
US_Sales = [7845,4512,3652,7452]
Sales = np.array ([EU_Sales, APAC_Sales,US_Sales])

print (Sales)


rigion_dict ={'Eu':0,'APAC':1,'US':2}
qu_dict ={'Q1':0,'Q2':1,'Q3':2,'Q4':3}

print(rigion_dict)
print(qu_dict)

Sales[rigion_dict['APAC']][qu_dict['Q3']]

[[1002 4523 4123 3584]
 [7854 9654 4582 8543]
 [7845 4512 3652 7452]]
{'Eu': 0, 'APAC': 1, 'US': 2}
{'Q1': 0, 'Q2': 1, 'Q3': 2, 'Q4': 3}


4582

In [58]:
print(Sales[rigion_dict["US"]][qu_dict['Q3']])


3652


In [59]:
Sales[rigion_dict['US']]

array([7845, 4512, 3652, 7452])

In [60]:
print(Sales[rigion_dict['Eu']][qu_dict['Q4']])

3584


In [64]:
a =np.arange(100)

print(a[10:],'\n')

print(a[1:40],'\n')


print(a[20:50:5],'\n')


print(a[::10])



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99] 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39] 

[20 25 30 35 40 45] 

[ 0 10 20 30 40 50 60 70 80 90]


In [65]:
arr1 =  np.arange(20)
print (arr1)

arr_slice = slice (1,10,2)
print (arr_slice)


print (arr1[arr_slice])



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
slice(1, 10, 2)
[1 3 5 7 9]


In [66]:
arr1 =  np.arange(20)
print (arr1)
arr_slice = slice (1,20,3)

print (arr1[arr_slice])



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  4  7 10 13 16 19]


In [67]:
a =np.arange(50)

print(a[30:],'\n')


print(a[arr_slice])

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

[ 1  4  7 10 13 16 19]


In [71]:
arr=np.arange(9)
arr=arr.reshape(3,3)

print(arr)

print('............................')

arr2 = arr[1:2]
print (arr2)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
............................
[[3 4 5]]


In [72]:
arr2 = arr[1:2,1:2]
print (arr2)


[[4]]


In [73]:
arr = np.arange(50)


print(arr[20:41:3])

[20 23 26 29 32 35 38]


In [81]:
arr1 =  np.arange(9)
print (arr1)

arr1=arr1.reshape(3,3)
print ('\n')
print (arr1)

print ('\n')
arr2 = arr1[0:2,0:2]

print (arr2)


[0 1 2 3 4 5 6 7 8]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 1]
 [3 4]]


In [82]:
arr = np.arange(5,14)
arr
arr1 = arr.reshape(3,3)
arr1

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [83]:
arr1[:,0:2]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [84]:
arr1[:,1:3]

array([[ 6,  7],
       [ 9, 10],
       [12, 13]])

In [96]:
print(arr1[1:])

[[ 8  9 10]
 [11 12 13]]


In [97]:
print(arr1.shape)

(3, 3)


In [98]:
print(arr1.ndim)

2


In [99]:
print(arr1.size)

9


In [100]:
print(arr1.min())

5


In [101]:
print(arr1.max())

13


In [102]:
print(arr1.sum())

81


In [103]:
print(np.std(arr1))

2.581988897471611


In [104]:
arr1.std()

2.581988897471611

In [105]:
print(np.sqrt(arr1))

[[2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128]]


In [106]:
print(arr1.size)

9


In [107]:
print(arr1.itemsize)

4


In [108]:
print(arr1.dtype)

int32


In [109]:
x =np.empty([3,4],dtype=int)

print(x)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [117]:
x =np.empty([3,4],dtype=float)

print(x)

[[50.         46.36363636 43.33333333 40.76923077]
 [ 5.          5.23809524  5.45454545  5.65217391]
 [ 6.66666667  6.77419355  6.875       6.96969697]]


In [118]:
x =np.empty([3,4],dtype=bool)

print(x)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [119]:
x =np.empty([3,4],dtype=str)

print(x)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [ ]:
np.savetxt('Sample.txt',arr1)

In [ ]:
np.loadtxt('Sample.txt')

In [ ]:
np.savetxt('Sample.csv',arr2,delimiter=';')


In [ ]:
arr1 = np.arange (9)
arr2 = arr1.reshape (3,3)
np.savetxt('Sample.txt',arr2)


arr3=np.loadtxt('Sample.txt')

print (arr3)


In [ ]:
np.savetxt ('Sample2.csv',arr2,delimiter = ';' )

In [ ]:
arr5=np.loadtxt('Sample.csv', delimiter = ';')

print (arr5)



In [120]:
for name in dir(numpy):
    print (name, end = '\t')   



ALLOW_THREADS	AxisError	BUFSIZE	Bytes0	CLIP	ComplexWarning	DataSource	Datetime64	ERR_CALL	ERR_DEFAULT	ERR_IGNORE	ERR_LOG	ERR_PRINT	ERR_RAISE	ERR_WARN	FLOATING_POINT_SUPPORT	FPE_DIVIDEBYZERO	FPE_INVALID	FPE_OVERFLOW	FPE_UNDERFLOW	False_	Inf	Infinity	MAXDIMS	MAY_SHARE_BOUNDS	MAY_SHARE_EXACT	MachAr	ModuleDeprecationWarning	NAN	NINF	NZERO	NaN	PINF	PZERO	RAISE	RankWarning	SHIFT_DIVIDEBYZERO	SHIFT_INVALID	SHIFT_OVERFLOW	SHIFT_UNDERFLOW	ScalarType	Str0	Tester	TooHardError	True_	UFUNC_BUFSIZE_DEFAULT	UFUNC_PYVALS_NAME	Uint64	VisibleDeprecationWarning	WRAP	_NoValue	_UFUNC_API	__NUMPY_SETUP__	__all__	__builtins__	__cached__	__config__	__deprecated_attrs__	__dir__	__doc__	__expired_functions__	__file__	__getattr__	__git_version__	__loader__	__mkl_version__	__name__	__package__	__path__	__spec__	__version__	_add_newdoc_ufunc	_distributor_init	_financial_names	_globals	_mat	_pytesttester	_version	abs	absolute	add	add_docstring	add_newdoc	add_newdoc_ufunc	alen	all	allclose	alltrue	amax	amin	angle	an

In [121]:
arr = np.array([[5,-10,-2],[4,3,9]])

print(arr)

print(arr.ndim)

[[  5 -10  -2]
 [  4   3   9]]
2


In [122]:
arr1= arr*10
print(arr1)

[[  50 -100  -20]
 [  40   30   90]]


In [123]:
print(arr+arr1)

[[  55 -110  -22]
 [  44   33   99]]


In [124]:
print(arr1.dtype)

int32


In [125]:
print(arr1.shape)

(2, 3)


In [126]:
data= [6,7.5,8,0,1]
arr2 =np.array(data)
print(arr2)

[6.  7.5 8.  0.  1. ]


In [127]:
print(type(arr2))

<class 'numpy.ndarray'>


In [128]:
data = np.array([[2,3,5],[5,9,10]])

print(data)

print(data.shape)

print(data.ndim)

[[ 2  3  5]
 [ 5  9 10]]
(2, 3)
2


In [129]:
data1 = [[10,9,8,7],[6,5,4,3,]]

data2 = np.array(data1)

print(data2)

print(data2.ndim)


[[10  9  8  7]
 [ 6  5  4  3]]
2


In [130]:
ar = np.zeros(50)

print(ar)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [134]:
arr = np.zeros((5,3))

print(arr,'\n')

print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

float64


In [135]:
ar = np.zeros(9)
arr1 =ar.reshape(3,3)


print(ar)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [170]:
arr3= np.empty((2, 3, 2))


print (arr3)
print (arr3.dtype)


[[[50.         46.36363636]
  [43.33333333 40.76923077]
  [ 5.          5.23809524]]

 [[ 5.45454545  5.65217391]
  [ 6.66666667  6.77419355]
  [ 6.875       6.96969697]]]
float64


In [171]:
arr3= np.empty((2, 3, 2),dtype=int)


print (arr3)
print (arr3.dtype)


[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]
int32


In [173]:
rang =np.arange(15)

print(rang)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [178]:
list1= [10,20,30]
arr1=  np.array(list1)

arr1[1] =50
print (list1)

print (arr1)



[10, 20, 30]
[10 50 30]


In [181]:
list1= [10,20,30]
arr1=  np.array(list1)
arr2 =np.asarray(arr1)

arr2[1] =500

print (list1)
print (arr1)
print (arr2)


[10, 20, 30]
[ 10 500  30]
[ 10 500  30]


In [189]:
list1= [10,20,30]
arr11=  np.array(list1)
arr12 =np.copy(arr11)

arr12[1] =100

print (list1)
print (arr11)
print (arr12)


[10, 20, 30]
[10 20 30]
[ 10 100  30]


In [190]:
a= np.arange(30)
a=a.reshape(3,10)

print (a,'\n')

x=np.ones_like(a)

print (x)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] 

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [192]:
st1 = np.array ([['A','B','C'], ['X','Y','Z']])
print (st1)

st2= np.ones_like(st1)
print (st2)


[['A' 'B' 'C']
 ['X' 'Y' 'Z']]
[['1' '1' '1']
 ['1' '1' '1']]


In [193]:
a= np.arange(30)
a=a.reshape(3,10)

print (a)

x=np.zeros_like(a)

print (x)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [194]:
x = np.empty ([5,2])

print (x)


[[2.12199579e-314 6.36598737e-314]
 [1.06099790e-313 1.48539705e-313]
 [1.90979621e-313 2.33419537e-313]
 [2.75859453e-313 3.18299369e-313]
 [3.60739285e-313 4.03179200e-313]]


In [195]:

a = ([1,2,3], [4,5,6]) 
x= np.empty_like(a)


print (x)


[[621007248       407         0]
 [        0         1         0]]


In [196]:

a = ([1,2,3], [4,5,6]) 
x= np.empty_like(a)
print (x)



[[620309936       407         0]
 [        0    131074         0]]


In [197]:
a = np.eye(5,dtype=int)

print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [198]:
a = np.eye(10,dtype=int)

print(a)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [199]:
b  = np.eye(4,dtype=float)

print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [202]:
a = np.eye(5)

print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [203]:
ar = np.array([1,2,3],dtype=np.float64)
ar1 = np.array([1,2,3],dtype=np.int32)

print(ar)
print(ar.dtype)

print('>>>>>>>>>>>>>>')

print(ar1)
print(ar1.dtype)

[1. 2. 3.]
float64
>>>>>>>>>>>>>>
[1 2 3]
int32


In [205]:
arr = np.array([1, 2, 3, 4, 5]) 


print (arr)
print (arr.dtype)
print ('\n')

float_arr = arr.astype(np.float64) 
print (float_arr)
print (float_arr.dtype)


[1 2 3 4 5]
int32


[1. 2. 3. 4. 5.]
float64


In [206]:
str_ar = np.array([1,5,3,-9.5,10.15],dtype=np.string_)

print(str_ar)

print(type(str_ar))

[b'1' b'5' b'3' b'-9.5' b'10.15']
<class 'numpy.ndarray'>


In [207]:
numeric_strings = np.array(['1.25','-9.6','42'], dtype=np.string_)

print (numeric_strings)
print (numeric_strings.dtype)

print ('\n')
float_values = numeric_strings.astype(float)
print (float_values)
print (float_values.dtype)


print('\n')
bool_values=float_values.astype(bool)
print(bool_values)

[b'1.25' b'-9.6' b'42']
|S4


[ 1.25 -9.6  42.  ]
float64


[ True  True  True]


In [208]:
arr = np.array([3.7, -1.2,-2.6,0.5,12.9,10.1])


print (arr)
print (arr.dtype)
print ('\n')

arr =arr.astype(np.int32)
print (arr)
print (arr.dtype)
print ('\n')


[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
float64


[ 3 -1 -2  0 12 10]
int32




In [209]:
int_array = np.arange(10)

print (int_array)
print (int_array.dtype)
print ('\n')

int_re =int_array.reshape((5,2))


print(int_re)
print ('\n')
float_array = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)


# Converting to another array type 
int_array=int_array.astype (float_array.dtype)


print (int_array)
print (int_array.dtype)
print ('\n')


[0 1 2 3 4 5 6 7 8 9]
int32


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64




In [210]:
arr = np.array([5,3,1,8,6])

print(np.sort(arr))

print(len(arr))



[1 3 5 6 8]
5


In [211]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print (arr)
print('\n')

print (np.sort(arr, axis = 0))
print('\n')

print (np.sort(arr, axis = 1))
print('\n')

[[3 2 4]
 [5 0 1]]


[[3 0 1]
 [5 2 4]]


[[2 3 4]
 [0 1 5]]




In [212]:
arr

array([[3, 2, 4],
       [5, 0, 1]])

In [214]:
random = np.random.random((5,5))
print(random)

[[0.47678943 0.3863524  0.9931961  0.56873365 0.75998392]
 [0.76244166 0.74591146 0.10396604 0.01193031 0.20610676]
 [0.75682641 0.69885864 0.1380087  0.45810246 0.09308898]
 [0.84839488 0.54595018 0.97151971 0.49929753 0.14450047]
 [0.84471452 0.29849203 0.4220266  0.6126469  0.2720913 ]]


In [215]:
data2 = [[1, 2,3, 4], [5,6,7, 8]]
arr2 = np.array(data2)


print (arr2)
print (arr2.ndim)
print (arr2.shape)



[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
