In [1]:
import numpy as np



In [9]:
list1 = [[10,20,30],[50,60,70]]
print ("This is the List form: ",list1)

a= np.array ([[10,20,30],[50,60,70]])
print ("This is the Array form: ", )



This is the List form:  [[10, 20, 30], [50, 60, 70]]
This is the Array form: 


In [34]:
a= np.array ([[10,20,30],[50,60,70]])
print (a)


[[10 20 30]
 [50 60 70]]


In [35]:
ar=np.array([[10,20,30],[50,60,70]])

In [36]:
ar

array([[10, 20, 30],
       [50, 60, 70]])

In [39]:
arr1=np.array([[10,20,30,40],[50,60,70,np.nan]])
arr1

array([[10., 20., 30., 40.],
       [50., 60., 70., nan]])

In [40]:
arr1=np.array([[10,20,30,40],[50.5,60,70,np.nan]])
arr1

array([[10. , 20. , 30. , 40. ],
       [50.5, 60. , 70. ,  nan]])

In [45]:
type(arr1[0][2])

numpy.float64

In [46]:
list1= [10, 20, 30.5,True, False, 'John']
x = np.array(list1)
print (x)

['10' '20' '30.5' 'True' 'False' 'John']


In [48]:
print (type(x[1]))

<class 'numpy.str_'>


In [49]:
   x[2]

'30.5'

In [52]:
x.ndim

1

In [53]:
arr1.ndim

2

In [54]:
x = np.array([[10,20,30],
              [10,20,30],
              [10,20,30],
               [10,20,30]
              ])
print (x)

[[10 20 30]
 [10 20 30]
 [10 20 30]
 [10 20 30]]


In [55]:
x.ndim

2

In [56]:
x.shape

(4, 3)

In [59]:
l1=[20,40,60]
l2=[70,80,100]
arr2=np.array([l1,l2])
print(arr2)

[[ 20  40  60]
 [ 70  80 100]]


In [61]:
Tup1 = (10,20,30,40,50,'x','y')

array1 = np.array (Tup1)

print (type(array1))
print (type(Tup1))

print (Tup1)
print (array1)


<class 'numpy.ndarray'>
<class 'tuple'>
(10, 20, 30, 40, 50, 'x', 'y')
['10' '20' '30' '40' '50' 'x' 'y']


In [71]:
l3=[10,20,30,40,50]

ar=np.array(l3)
ar1=ar[2:]
ar1[1]=45

print('do not impact the list :',l3)
print('the impact list :',ar1)

do not impact the list : [10, 20, 30, 40, 50]
the impact list : [30 45 50]


In [81]:
ar2=np.array(ar1)
ar3=ar2[:]

ar3[2]=500

print(ar3)
print(ar2)

[ 30  45 500]
[ 30  45 500]


In [88]:
arr3=np.array(l3).copy()
arr3

array([10, 20, 30, 40, 50])

In [90]:
arr3[[2,3]]=[[35,45]]

In [91]:
arr3

array([10, 20, 35, 45, 50])

In [92]:
l3

[10, 20, 30, 40, 50]

In [94]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [97]:
b=a.reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [107]:
b=np.ones((5,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [108]:
m=np.arange(0,30)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [110]:
m=np.arange(0,30)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [112]:
m1=np.reshape(m,(3,10),'F')

In [113]:
m1

array([[ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29]])

In [115]:
m1=np.reshape(m,(3,10),'A')

In [116]:
m1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [119]:
list1 = [10,20,30,40]
list2 = [100,110,120,130]
list3 = [200,210,220,230]

ar=np.array([list1,list2,list3])


print(ar)

[[ 10  20  30  40]
 [100 110 120 130]
 [200 210 220 230]]


In [122]:
print(ar.T)

[[ 10 100 200]
 [ 20 110 210]
 [ 30 120 220]
 [ 40 130 230]]


In [123]:
list1 = [500,510,520,530]
list2 = [100,110,120,130]
list3 = [200,210,220,230]
Mat1 = np.array ([list1, list2,list3])

list6 = [10,11,12,13]
list7 = [20,21,22,23]
list8 = [30,31,32,33]
Mat2 = np.array ([list6, list7,list8])


In [126]:
print(Mat1/Mat2)

[[50.         46.36363636 43.33333333 40.76923077]
 [ 5.          5.23809524  5.45454545  5.65217391]
 [ 6.66666667  6.77419355  6.875       6.96969697]]


In [127]:
print(Mat1//Mat2)

[[50 46 43 40]
 [ 5  5  5  5]
 [ 6  6  6  6]]


In [128]:
print(Mat1*Mat2)

[[5000 5610 6240 6890]
 [2000 2310 2640 2990]
 [6000 6510 7040 7590]]


In [129]:
print(Mat1-Mat2)

[[490 499 508 517]
 [ 80  89  98 107]
 [170 179 188 197]]


In [134]:
print(Mat2.ravel())

[10 11 12 13 20 21 22 23 30 31 32 33]


In [136]:
x=np.linspace(0,20,4)
x

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [6]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)

[[10 20 30]
 [40 50 60]]


In [7]:
print(arr.T)

[[10 40]
 [20 50]
 [30 60]]


In [15]:
india=[10000,15000,20000,25000]
bangladesh=[12000,15600,18000,25400]
pakisthan=[80000,90000,11000,14000]
nepal=[5000,7000,8500,10000]

Sales=np.array([india,bangladesh,pakisthan,nepal])


Country={'india':0,'bangladesh':1,'pakisthan':2,'nepal':3}
Sales_report={'Q1':0,'Q2':1,'Q3':2,'Q4':3}


In [19]:
Sales[Country['india'],Sales_report['Q3']]

20000

In [21]:
print(Sales[Country['bangladesh'],Sales_report['Q2']])

15600


In [24]:
arr1= np.arange (100)
print (arr1[10:],'\n')
print (arr1[:20],'\n')
print (arr1[10:20],'\n')
print (arr1[10:50:5])
print (arr1[::10])


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[10 11 12 13 14 15 16 17 18 19] 

[10 15 20 25 30 35 40 45]
[ 0 10 20 30 40 50 60 70 80 90]


In [25]:
arr1 =  np.arange(20)
print (arr1)

arr_slice = slice (1,10,2)

print (arr_slice)
print (arr1[arr_slice])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
slice(1, 10, 2)
[1 3 5 7 9]


In [26]:
arr1 =  np.arange(9)
print (arr1)

arr1=arr1.reshape(3,3)
print ('\n')

print (arr1)
print ('\n')

arr2 = arr1[0:2,0:2]
print (arr2)



[0 1 2 3 4 5 6 7 8]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 1]
 [3 4]]


In [27]:

arr1 =  np.arange(9)
arr1=arr1.reshape(3,3)

print (arr1)
print ('\n')

arr2 = arr1[1:3,1:3]
print (arr2)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[4 5]
 [7 8]]


In [31]:
print ('\n')
arr2 = arr1[0:3,1:2]
print (arr2)



[[1]
 [4]
 [7]]


In [37]:
arr1.itemsize

4

In [38]:
arr1.size

9

In [39]:
arr1.min()

0

In [40]:
arr1.max()

8

In [43]:
np.sqrt(arr1)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [46]:
arr5 = np.empty([3,2], dtype =  float)
print (arr5,'\n')

arr5 = np.empty([3,2], dtype =  int)
print (arr5,'\n')

arr5 = np.ones([3,2], dtype =  int)
print (arr5,'\n')

arr5 = np.empty([3,2], dtype =  bool)
print (arr5,'\n')

arr5 = np.empty([3,2], dtype =  str)
print (arr5,'\n')



[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[[0 0]
 [0 0]
 [0 0]] 

[[1 1]
 [1 1]
 [1 1]] 

[[False False]
 [False False]
 [False False]] 

[['' '']
 ['' '']
 ['' '']] 



In [53]:
a =np.arange(10,100,10)
data=a.reshape(3,3)
np.savetxt('data.csv',data)

In [56]:
data=np.loadtxt('data.csv')
data

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [58]:
type(data)

numpy.ndarray

In [3]:
ar1=np.array([[10,20,30,40],[50,60,70,80]])


print(ar1)
print(ar1.ndim)

[[10 20 30 40]
 [50 60 70 80]]
2


In [4]:
print(ar1*10)

[[100 200 300 400]
 [500 600 700 800]]


In [7]:
data1=ar1+ar1

print(data1)

[[ 20  40  60  80]
 [100 120 140 160]]


In [13]:
print(ar1.dtype)

int32


In [14]:
ar1.shape

(2, 4)

In [16]:
d=[2,4,6,8]
data=np.array(d)
data

array([2, 4, 6, 8])

In [17]:
type(data)

numpy.ndarray

In [24]:
data1=np.array([[8,5,3],[1,6,9]])

print(data1)
print('No of Array :','\n',data1.ndim)
print('Shape of Array :','\n',data1.shape)

[[8 5 3]
 [1 6 9]]
No of Array : 
 2
Shape of Array : 
 (2, 3)


In [25]:
data2=np.zeros(10)

print(data2)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
data2=np.zeros((3,5))

print(data2)

print('Data type is :','\n',ar1.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Data type is : 
 int32


In [35]:
data3=np.empty((2,3,2))
print(data3)


[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [38]:
data2=np.ones((3,5,2))
data2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [41]:
data4=np.arange(10,20)
data4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
list1= [10,20,30]
arr1=np.array(list1)
arr2=np.array(arr1)
arr2[1]=500


print(arr1)
print(arr2)
print(list1)

[10 20 30]
[ 10 500  30]
[10, 20, 30]


In [54]:
list1= [10,20,30]
arr1=  np.array(list1)
arr11= np.array(arr1)
arr11[1] =100


print (list1)
print (arr1)
print (arr11)


[10, 20, 30]
[10 20 30]
[ 10 100  30]


In [58]:
list2= [10,20,30]
arr11=np.asarray(list2)
arr22=np.asarray(arr11)
arr22[2]=400


print (list2)
print (arr11)
print (arr22)


[10, 20, 30]
[ 10  20 400]
[ 10  20 400]


In [64]:
a= np.arange(30)
a=a.reshape(3,10)

print (a,'\n')

x=np.ones_like(a)
print (x)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] 

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [68]:

a= np.arange(30)
a=a.reshape(3,10)

print (a)
x=np.zeros_like(a)

print (x)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [71]:
x = np.empty ([5,2])
print (x)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [73]:
a = ([[1,2,3], [4,5,6]]) 
x= np.empty_like(a)
print (x)


[[1163446448        587          0]
 [         0          1          0]]


In [74]:
x = np.eye(5, dtype=int)
print (x)


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [75]:
xx = np.eye(5, dtype=str)
print (xx)


[['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']
 ['' '' '' '' '1']]


In [77]:
xx = np.eye(10, dtype=float)
print (xx)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [78]:
xx = np.eye(5, dtype=bool)
print (xx)


[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


In [81]:
x = np.identity(4, dtype=float)
print (x)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [89]:
ar=np.array([10,20,30],dtype=np.float64)

print(ar)
print(ar.dtype)

[10. 20. 30.]
float64


In [91]:
ar1=np.array([10,20,30],dtype=np.int64)

print(ar1)
print(ar1.dtype)

[10 20 30]
int64


In [94]:
arr = np.array([1, 2, 3, 4, 5]) 

print (arr)
print (arr.dtype)

print ('\n')

float_to_int=arr.astype(np.float64)
print(float_to_int)

[1 2 3 4 5]
int32


[1. 2. 3. 4. 5.]


In [98]:
arr = np.array([3.7, -1.2,-2.6,0.5,12.9,10.1])


print (arr)
print (arr.dtype)
print ('\n')

arr =arr.astype(np.int32)
print (arr)
print (arr.dtype)


[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
float64


[ 3 -1 -2  0 12 10]
int32


In [103]:
numeric_strings = np.array(['1.25','-9.6','42','5.5','1'], dtype=np.string_)


print (numeric_strings)
print (numeric_strings.dtype)

print ('\n')


float_values = numeric_strings.astype(float)
print (float_values)
print (float_values.dtype)


[b'1.25' b'-9.6' b'42' b'5.5' b'1']
|S4


[ 1.25 -9.6  42.    5.5   1.  ]
float64


In [113]:
int_array = np.arange(10)

print (int_array)
print (int_array.dtype)

print ('\n')


float_array = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
# Converting to another array type 
int_array=int_array.astype (float_array.dtype)


print (int_array)
print (int_array.dtype)
print ('\n')
print(float_array)


[0 1 2 3 4 5 6 7 8 9]
int32


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


[0.22  0.27  0.357 0.38  0.44  0.5  ]


In [119]:
a=np.array(float_array,dtype=np.str_)

print(a)

['0.22' '0.27' '0.357' '0.38' '0.44' '0.5']


In [121]:
a=np.array(float_array,dtype=bool)

print(a)

[ True  True  True  True  True  True]
